### ISSUE TITLE
Add gate visualisations for `OpType.CnRx` and `OpType.CnRz`

### ISSUE THREAD

**Issue by CalMacCQ** [CQCL/pytket-circuit-renderer#62]
The CnRx and CnRz gates have been added in pytket v1.29. The CnRy gate has been a member of `OpType` for sometime and has the following visualisation.

![CnRy2](https://github.com/CQCL/pytket-circuit-renderer/assets/93673602/00d82106-dc7e-4b28-9c17-a08d16ea1381)

Currently CnRx and CnRz look like boxes. It would be nice to update them.

![circ](https://github.com/CQCL/pytket-circuit-renderer/assets/93673602/a251e94a-274b-4030-968b-e63b0b0dc401)

**Comment by DNA386** [comment]
https://github.com/CQCL/pytket-circuit-renderer/pull/63
